title: FRC 7913 Programming
description: For the 2024 season, Bearly Functioning's programming team is covering all its decisions here
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Robot Code: https://github.com/FRC-7913/Crescendo-2024/
